function final = impq4(filename, dataLines)
%IMPORTFILE Import data from a text file
%  FINAL = IMPORTFILE(FILENAME) reads data from text file FILENAME for
%  the default selection.  Returns the data as a table.
%
%  FINAL = IMPORTFILE(FILE, DATALINES) reads data for the specified row
%  interval(s) of text file FILENAME. Specify DATALINES as a positive
%  scalar integer or a N-by-2 array of positive scalar integers for
%  dis-contiguous row intervals.
%
%  Example:
%  final = importfile("C:\Users\usuario\Documents\MATLAB\FEA-axisymmetric\final.dat", [1, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 01-Dec-2023 11:21:24

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [1, Inf];
end

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 7);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["GRID", "VarName2", "VarName3", "VarName4", "VarName5", "VarName6", "VarName7"];
opts.VariableTypes = ["categorical", "double", "double", "double", "double", "double", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Specify variable properties
opts = setvaropts(opts, "GRID", "EmptyFieldRule", "auto");
opts = setvaropts(opts, ["VarName2", "VarName3", "VarName4", "VarName5", "VarName6", "VarName7"], "ThousandsSeparator", ",");

% Import the data
final = readtable(filename, opts);

x = final.VarName4(final.GRID == 'GRID');
y = final.VarName6(final.GRID == 'GRID');

msh.nodes = [x,y];

msh.elements = [final.VarName4(final.GRID == 'CQUADX4'),final.VarName5(final.GRID == 'CQUADX4'),final.VarName6(final.GRID == 'CQUADX4'),final.VarName7(final.GRID == 'CQUADX4')];

msh.bcond.fijoz = final.VarName3(final.GRID == 'SPC' & final.VarName4 == 3);
msh.bcond.fijox = final.VarName3(final.GRID == 'SPC' & final.VarName4 == 15); % porque 15???

final = msh;
end