function sal=impq8(txt)

%% Import data from text file
% Script for importing data from the following text file:
%
%    filename: D:\2do cuat 2021\finitos\TP2\data9.dat
%
% Auto-generated by MATLAB on 10-Oct-2022 23:13:06

%% Setup the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 10);

% Specify range and delimiter
opts.DataLines = [1, Inf];
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["VN1", "VN2", "VN3", "VN4", "VN5", "VN6", "VN7", "VN8", "VN9", "Var10"];
opts.SelectedVariableNames = ["VN1", "VN2", "VN3", "VN4", "VN5", "VN6", "VN7", "VN8", "VN9"];
opts.VariableTypes = ["categorical", "double", "double", "double", "double", "double", "double", "double", "double", "string"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Specify variable properties
opts = setvaropts(opts, "Var10", "WhitespaceRule", "preserve");
opts = setvaropts(opts, ["VN1", "Var10"], "EmptyFieldRule", "auto");

% Import the data
data9 = readtable(txt, opts);
cord=[data9.VN4(data9.VN1=='GRID'),data9.VN5(data9.VN1=='GRID'),data9.VN6(data9.VN1=='GRID')];
type=data9.VN1(~((data9.VN1=='GRID')+(data9.VN1=='+')));
nod=[data9.VN4(data9.VN1==type(1)),data9.VN5(data9.VN1==type(1)),data9.VN6(data9.VN1==type(1)),data9.VN7(data9.VN1==type(1)),data9.VN8(data9.VN1==type(1)),...
    data9.VN9(data9.VN1==type(1)),data9.VN2(data9.VN1=='+'),data9.VN3(data9.VN1=='+'),];
nelem=data9.VN2(data9.VN1==type(1));
nod=sortrows([nelem,nod],1);nod=nod(:,2:end);
bcond.num = data9.VN3(data9.VN1=='SPC');
bcond.dir = data9.VN4(data9.VN1=='SPC');
loads.EleNum = data9.VN3(data9.VN1=='PLOADX1');
loads.NodNum = [data9.VN6(data9.VN1=='PLOADX1'),data9.VN7(data9.VN1=='PLOADX1')];
msh.pointLoad.EleNum = data9.VN3(data9.VN1=='FORCE');
msh.pointLoad.dir = [data9.VN6(data9.VN1=='FORCE'),data9.VN8(data9.VN1=='FORCE')];

msh.cord=cord;
msh.elem.type=type;
msh.elem.nod=nod;
msh.bcond = bcond;
msh.loads = loads;
clear nod cord type bcond
sal=msh;
%% Clear temporary variables
clear opts data9
end